# Generated by Django 4.0.4 on 2024-07-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aLeadToDentist', '0002_funcionario_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='contato_emergencia_nome',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='contato_emergencia_telefone',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='foto_perfil',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
