# Generated by Django 4.0.4 on 2024-07-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aLeadToDentist', '0003_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_pics/'),
        ),
    ]
